# Generated by Django 5.2.6 on 2025-09-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la ciudad', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Código IATA de la ciudad', max_length=3, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción de la ciudad', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el destino está disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
                'ordering': ['name'],
            },
        ),
    ]
