# Generated by Django 5.2.6 on 2025-09-28 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateField(help_text='Fecha del viaje')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('reserved', 'Reservada'), ('cancelled', 'Cancelada'), ('completed', 'Completada')], default='pending', help_text='Estado de la solicitud', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales del usuario', null=True)),
                ('operator_notes', models.TextField(blank=True, help_text='Notas del operador', null=True)),
                ('reserved_at', models.DateTimeField(blank=True, help_text='Fecha y hora de reserva', null=True)),
                ('notification_sent', models.BooleanField(default=False, help_text='Indica si se envió la notificación de recordatorio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(help_text='Destino del vuelo', on_delete=django.db.models.deletion.CASCADE, related_name='flight_requests', to='destinations.destination')),
                ('reserved_by', models.ForeignKey(blank=True, help_text='Operador que reservó el vuelo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_flights', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Usuario que realiza la solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='flight_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Vuelo',
                'verbose_name_plural': 'Solicitudes de Vuelo',
                'ordering': ['-created_at'],
            },
        ),
    ]
